language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - black .
  - flake8 .
  - coverage run manage.py test

after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "Encrypted <access-key-id>=AKIAUQCXHFK6XW3ABNBA"
  secret_access_key:
    secure: "Encypted <secret-access-key>=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"
  region: "us-west-2"
  app: "django-tutorial"
  env: "django-env"
  bucket_name: "the-target-S3-bucket"
