language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - black .
  - flake8 .
  - coverage run manage.py test

after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAUQCXHFK6W3V2G64X
  secret_access_key: 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
  #    secure: "Encypted <secret-access-key>=YUH+mxnJhvAbQ2Ake4vPLpISdZypRZmsr+wO2PdY"
  region: "us-west-2"
  app: "django-tutorial"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-west-2-309420567229"
  on:
    all_branches: true
